import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <section>
              <div className="container px-5 py-24 mx-auto">
                  <div className="flex flex-col text-center w-full mb-12">
                      <h1 className="sm:text-3xl text-2xl font-extrabold title-font mb-4">Change Your Life</h1>
                      <p className="lg:w-2/3 mx-auto leading-relaxed text-base">Whatever cardigan tote bag tumblr
                          hexagon brooklyn asymmetrical gentrify, subway tile poke farm-to-table. Franzen you probably
                          haven't heard of them man bun deep.</p>
                  </div>
              </div>
          </section>
      </main>
    </div>
  )
}
